// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2KZNieLo_faNFErK5-CFvvWhrvBmisOA',
    appId: '1:883147489769:android:d7748e4cd45d66f1904b78',
    messagingSenderId: '883147489769',
    projectId: 'plantcare-36516',
    storageBucket: 'plantcare-36516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWrVAt7BuCUYAmCDsRx5kUgjdWXWRKfds',
    appId: '1:883147489769:ios:7d282a3ba0439beb904b78',
    messagingSenderId: '883147489769',
    projectId: 'plantcare-36516',
    storageBucket: 'plantcare-36516.appspot.com',
    androidClientId: '883147489769-6llfdn1l916qm7snkol7e2t34nqnv4kt.apps.googleusercontent.com',
    iosClientId: '883147489769-mt6dkkp8qlm4bi2numrouini44qi1fiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantCare',
  );

}